spring:
  application:
    name: ai-agent-backend
  profiles:
    active: local
  ai:
    chat:  # 对话记忆
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:  # pgsql中的向量数据库配置
      pgvector:
        index-type: HNSW
        dimensions: 1024
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        initialize-schema: true
#    mcp:
#      client:
#        sse:
#          connections:
#            image-search:   # 可以同时配置多个服务端
##              url: http://localhost:8082 # 换成你服务端实际运行的地址
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

server:
  port: 8081
  servlet:
    context-path: /api
# 用来初始化知识库
app:
  init-vectorstore: false  # 导完数据手动改成 false
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wxl.agent.controller
# knife4j的增强配置，不需要增强可以不配， http://localhost:8081/api/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn